### ISSUE TITLE
How to modify the software and make a reference to call HLA types from mouse species?

### ISSUE THREAD

**Issue by plsysu** [TRON-Bioinformatics/seq2HLA#2]
Hi,

How to modify the software and make a reference to call HLA types from mouse species?

Thanks!

**Comment by sebboegel** [comment]
Thank you very much for your interest in seq2HLA. However, seq2HLA is specifically designed for typing Human Leukocyte Antigens (HLA) types and can therefore not easily adapted to the much less homozygous MHC system in mice (H2). You might have a look at https://pubmed.ncbi.nlm.nih.gov/29858815/. I hope that helps.

Best, 

Sebastian

**Comment by plsysu** [comment]
Thank you！
