### ISSUE TITLE
ClassI-class-2nditeration_1.fq empty

### ISSUE THREAD

**Issue by peterthorpe5** [TRON-Bioinformatics/seq2HLA#4]
Dear seq2HLA,

I installed the requisites through conda, however, when I try to run this is always stops after the first iteration. Therefore, ClassI-class-2nditeration_1.fq is always empty. This is the same for ~20 cell lines. (RNAseq fq input). 

An example bowtie log is:
# reads processed: 8494272
# reads with at least one reported alignment: 660 (0.01%)
# reads that failed to align: 8493612 (99.99%)
Reported 49859 paired-end alignments to 1 output stream(s)

bowtie version 1.1.2

please could you point me in the direction of a fix?

REgards,

Peter Thorpe

**Comment by sebboegel** [comment]
Dear Peter,

sorry for the late reply. Is the issue still an issue?
How does the HLA class I typing text file looks like?

Best,

Sebastian

**Comment by peterthorpe5** [comment]
Hi Sebastian,

Thank you very much for your reply. I am sorry this project has finished now for me .... I cannot replicate the work without getting access to the data again. 

cheers,

Pete
